### ISSUE TITLE
DEDISgen

### ISSUE THREAD

**Issue by Kourpa** [jtpaulo/dedisbench#2] opened 2015-07-17 23:04 UTC
Segmentation Faults if run with a 300G file

**Comment by jtpaulo** [comment] 2015-07-18 11:41
Hi, 

Thank you for reporting this issue.

 In my e-mail I have received the following information for this issue: "Segmentation Faults if /gendb/, /gendb/duplicatedb and /gendb/printdb are not in the current working directory."

Is the segmentation fault of this issue related with the location of the folders or with the size of the file?

Regards, 

João Paulo

**Comment by CubeVato** [comment] 2015-08-03 18:44
Hi João,

I work with Kourpa. We're both part of Howard Marks' Other Other Operation. It appears to be an issue with the size. We're having some trouble reproducing it consistently. According to my notes, we were trying to run Gen on the temp files (dedisbench_0010test0, etc.) generated from an ~300Gb DEDISbench run with the -z flag enabled. On the first attempt, it reported that the db files were missing and segfaulted. We moved the db files to the correct location and ran it again, and it stopped complaining that it was missing files but then segfaulted anyway. We were later able to get it to work without issue by running it on the temp files from a run using the default file size, which leads me to think it's an issue with the size of the ~300Gb file. We haven't been able to get it working on directories that don't contain dedisbench_0010test0, etc. files. This might be related, or it might be a separate issue. If we run Gen with -f and select a folder that doesn't contain the dedisbench_0010test... files, Gen outputs 0 blocks read.

 I'll send you the exact output logs if I can get the test machine working again.

Regards,

Ramón A. Lovato

**Comment by jtpaulo** [comment] 2015-08-03 21:24
Hi Ramón, 

If I understood correctly, you are reporting three distinct bugs/errors
- The first is related to the DBs folders that are not created/specified correctly. This means that if you do not create them with the exact names specified in the code, DEDISgen will segfault.
- The second issue is when DEDISgen is used to analyze files with size superior to 300GB. Is there a single file with this size or the 300GB are the sum of sizes of several files? I am asking this because I have used DEDISgen for datasets with a size superior to 300GB but these datasets had several small files. 
- The third issue is that DEDISGen is not analyzing directories that do not contain the DEDISbench temp files. This issue is really strange, I need to find the problem. Once again, I have used this tool in the past for directories with regular files so, the problem must have been introduced in some commit.

Please confirm if these are the issues. Also if you can send any additional logs or information regarding the setup/commands you ran that you find useful, that would be nice.

Regards, 

João Paulo

**Comment by CubeVato** [comment] 2015-08-03 22:06
I will ask Kourpa for clarification and have him get back to you. Thanks!

**Comment by CubeVato** [comment] 2015-08-04 00:46
After some targeted debugging, we believe it's a permissions problem. Unfortunately, since DEDISgen segfaults without reporting where the problem occurred, we're having trouble determining which file it needs access to. We're in the process of generating a .ovf of the virtual machine. I'll email it to you when it's done, along with the logs.

**Comment by CubeVato** [comment] 2015-08-04 01:27
Hello João,

Ramón Lovato from DeepStorage here again. Attached, please find three log
files from different runs of DEDISgen. You should also have received an
email from Howard with a SugarSync link containing the .ovf of the virtual
machine we were testing it on, in case you'd like to take a look at that
(the VM's admin password is Passw0rd). As mentioned in the GitHub issue,
after some more testing, we believe this problem to be permissions-related,
but since Gen terminates without indicating which file it was trying to
access, we're having trouble identifying the culprit, especially after
going through and using chmod on all relevant directories and their
contents.

Regards,

Ramón A. Lovato

On Mon, Aug 3, 2015 at 3:24 PM, João Paulo notifications@github.com wrote:

> Hi Ramón,
> 
> If I understood correctly you are reporting three distinct bugs/errors
> 
>    -
> 
>    The first is related to the DBs folders that are not created/specified
>    correctly. This means that if you do not create them with the exact names
>    specified in the code, DEDISgen will segfault.
>    -
> 
>    The second issue is when DEDISgen is used to analyze files with size
>    superior to 300GB. Is there a single file with this size or the 300GB are
>    the sum of sizes of several files? I am asking this because I have used
>    DEDISgen for datasets with a size superior to 300GB but these datasets had
>    several small files.
>    -
> 
>    The third issue is that DEDISGen is not analyzing directories that do
>    not contain the DEDISbench temp files. This issue is really strange, I need
>    to find the problem. Once again, I have used this tool in the past for
>    directories with regular files so, the problem must have been introduced in
>    some commit.
> 
> Please confirm if these are the issues. Also if you can send any
> additional logs or information regarding the setup/commands you ran that
> you find useful, It would be nice.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jtpaulo/dedisbench/issues/2#issuecomment-127409748.

[dedis@dedisbenchcentos7 dedisbench-master]$ DEDISgen -f -p/ -o/home/dedis/Desktop 
Removing old databases
Initing new database
gendbs/duplicatedb/__db.001: No such file or directory
Error opening environment: No such file or directory
start processing folder /
files scanned 0
total blocks scanned 0
total blocks with zeros appended 0
blocks without duplicates 0
distinct blocks with duplicates 0
duplicated blocks 0
space saved 0
before generating output dist
gendbs/printdb/__db.001: No such file or directory
Error opening environment: No such file or directory
Segmentation fault (core dumped)

#####
Creating the directories with  mkdir -p gendbs/duplicatedb/ gendbs/printdb/ solves these two error messages.

[dedis@dedisbenchcentos7 dedisbench-master]$ ./DEDISgen -f -p/mnt/ -o/home/dedis/Desktop/
Removing old databases
Initing new database
start processing folder /mnt/
Processing /mnt/dedisbench_0010test1 
processed 100000 blocks
processed 200000 blocks
processed 300000 blocks
processed 400000 blocks
processed 500000 blocks
Processing /mnt/dedisbench-master/duplicatedist.c 
Processing /mnt/dedisbench-master/LICENSE 
Processing /mnt/dedisbench-master/config.h.in 
Processing /mnt/dedisbench-master/stamp-h1 
Processing /mnt/dedisbench-master/mkinstalldirs 
Processing /mnt/dedisbench-master/compile 
Processing /mnt/dedisbench-master/dist_archival 
Processing /mnt/dedisbench-master/dist_highperf 
Processing /mnt/dedisbench-master/AUTHORS 
Processing /mnt/dedisbench-master/random.c 
Processing /mnt/dedisbench-master/DEDISbench.c 
Processing /mnt/dedisbench-master/README 
Processing /mnt/dedisbench-master/Makefile.am 
Processing /mnt/dedisbench-master/randomgen/SFMT-params11213.h 
Processing /mnt/dedisbench-master/randomgen/SFMT.h 
Processing /mnt/dedisbench-master/randomgen/SFMT.c 
Processing /mnt/dedisbench-master/randomgen/SFMT-params216091.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params44497.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params2281.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params607.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-alti.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params132049.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params4253.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params86243.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params19937.h 
Processing /mnt/dedisbench-master/randomgen/Makefile.in 
Processing /mnt/dedisbench-master/randomgen/SFMT-params1279.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params.h 
Processing /mnt/dedisbench-master/randomgen/Makefile 
Processing /mnt/dedisbench-master/DEDISgen.c 
Processing /mnt/dedisbench-master/depcomp 
Processing /mnt/dedisbench-master/COPYING 
Processing /mnt/dedisbench-master/ChangeLog 
Processing /mnt/dedisbench-master/aclocal.m4 
Processing /mnt/dedisbench-master/config.status 
Processing /mnt/dedisbench-master/iodist.c 
Processing /mnt/dedisbench-master/configure.ac 
Processing /mnt/dedisbench-master/install-sh 
Processing /mnt/dedisbench-master/config.h.in~ 
Processing /mnt/dedisbench-master/config.log 
Processing /mnt/dedisbench-master/autom4te.cache/output.4 
Processing /mnt/dedisbench-master/autom4te.cache/output.0 
Processing /mnt/dedisbench-master/autom4te.cache/traces.3 
Processing /mnt/dedisbench-master/autom4te.cache/output.3 
Processing /mnt/dedisbench-master/autom4te.cache/traces.0 
Processing /mnt/dedisbench-master/autom4te.cache/traces.4 
Processing /mnt/dedisbench-master/autom4te.cache/requests 
Processing /mnt/dedisbench-master/autom4te.cache/traces.1 
Processing /mnt/dedisbench-master/autom4te.cache/output.1 
Processing /mnt/dedisbench-master/autom4te.cache/traces.2 
Processing /mnt/dedisbench-master/autom4te.cache/output.2 
Processing /mnt/dedisbench-master/README.mkd 
Processing /mnt/dedisbench-master/INSTALL 
Processing /mnt/dedisbench-master/config.h 
Processing /mnt/dedisbench-master/.bzrignore 
Processing /mnt/dedisbench-master/dist_personalfiles 
Processing /mnt/dedisbench-master/Makefile.in 
Processing /mnt/dedisbench-master/missing 
Processing /mnt/dedisbench-master/configure 
Processing /mnt/dedisbench-master/.DS_Store 
Processing /mnt/dedisbench-master/NEWS 
Processing /mnt/dedisbench-master/configure.scan 
Processing /mnt/dedisbench-master/berk.c 
Processing /mnt/dedisbench-master/.deps/DEDISgen-DEDISgen.Po 
Processing /mnt/dedisbench-master/.deps/DEDISgenutils-DEDISgen-utils.Po 
Processing /mnt/dedisbench-master/.deps/DEDISbench-DEDISbench.Po 
Processing /mnt/dedisbench-master/autoscan.log 
Processing /mnt/dedisbench-master/Makefile 
Processing /mnt/dedisbench-master/DEDISgen-utils.c 
Processing /mnt/dedisbench_0010test3 
processed 600000 blocks
processed 700000 blocks
processed 800000 blocks
processed 900000 blocks
processed 1000000 blocks
Processing /mnt/dedisbench_0010test2 
processed 1100000 blocks
processed 1200000 blocks
processed 1300000 blocks
processed 1400000 blocks
processed 1500000 blocks
Processing /mnt/dedisbench_0010test0 
processed 1600000 blocks
processed 1700000 blocks
processed 1800000 blocks
processed 1900000 blocks
processed 2000000 blocks
files scanned 73
total blocks scanned 2097616
total blocks with zeros appended 0
blocks without duplicates 840376
distinct blocks with duplicates 15142
duplicated blocks 1242098
space saved 5087633408
before generating output dist
before printing output dist
Segmentation fault (core dumped)

#####
Directories exist. Permissions for /mnt/ are set recursively to 775: chmod -R 775 /mnt/.

[dedis@dedisbenchcentos7 dedisbench-master]$ sudo ./DEDISgen -f -p/mnt/ -o/home/dedis/Desktop/
Removing old databases
Initing new database
start processing folder /mnt/
Processing /mnt/dedisbench_0010test1 
processed 100000 blocks
processed 200000 blocks
processed 300000 blocks
processed 400000 blocks
processed 500000 blocks
Processing /mnt/dedisbench-master/duplicatedist.c 
Processing /mnt/dedisbench-master/LICENSE 
Processing /mnt/dedisbench-master/config.h.in 
Processing /mnt/dedisbench-master/stamp-h1 
Processing /mnt/dedisbench-master/mkinstalldirs 
Processing /mnt/dedisbench-master/compile 
Processing /mnt/dedisbench-master/dist_archival 
Processing /mnt/dedisbench-master/dist_highperf 
Processing /mnt/dedisbench-master/AUTHORS 
Processing /mnt/dedisbench-master/random.c 
Processing /mnt/dedisbench-master/DEDISbench.c 
Processing /mnt/dedisbench-master/README 
Processing /mnt/dedisbench-master/Makefile.am 
Processing /mnt/dedisbench-master/randomgen/SFMT-params11213.h 
Processing /mnt/dedisbench-master/randomgen/SFMT.h 
Processing /mnt/dedisbench-master/randomgen/SFMT.c 
Processing /mnt/dedisbench-master/randomgen/SFMT-params216091.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params44497.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params2281.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params607.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-alti.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params132049.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params4253.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params86243.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params19937.h 
Processing /mnt/dedisbench-master/randomgen/Makefile.in 
Processing /mnt/dedisbench-master/randomgen/SFMT-params1279.h 
Processing /mnt/dedisbench-master/randomgen/SFMT-params.h 
Processing /mnt/dedisbench-master/randomgen/Makefile 
Processing /mnt/dedisbench-master/DEDISgen.c 
Processing /mnt/dedisbench-master/depcomp 
Processing /mnt/dedisbench-master/COPYING 
Processing /mnt/dedisbench-master/ChangeLog 
Processing /mnt/dedisbench-master/aclocal.m4 
Processing /mnt/dedisbench-master/config.status 
Processing /mnt/dedisbench-master/iodist.c 
Processing /mnt/dedisbench-master/configure.ac 
Processing /mnt/dedisbench-master/install-sh 
Processing /mnt/dedisbench-master/config.h.in~ 
Processing /mnt/dedisbench-master/config.log 
Processing /mnt/dedisbench-master/autom4te.cache/output.4 
Processing /mnt/dedisbench-master/autom4te.cache/output.0 
Processing /mnt/dedisbench-master/autom4te.cache/traces.3 
Processing /mnt/dedisbench-master/autom4te.cache/output.3 
Processing /mnt/dedisbench-master/autom4te.cache/traces.0 
Processing /mnt/dedisbench-master/autom4te.cache/traces.4 
Processing /mnt/dedisbench-master/autom4te.cache/requests 
Processing /mnt/dedisbench-master/autom4te.cache/traces.1 
Processing /mnt/dedisbench-master/autom4te.cache/output.1 
Processing /mnt/dedisbench-master/autom4te.cache/traces.2 
Processing /mnt/dedisbench-master/autom4te.cache/output.2 
Processing /mnt/dedisbench-master/README.mkd 
Processing /mnt/dedisbench-master/INSTALL 
Processing /mnt/dedisbench-master/config.h 
Processing /mnt/dedisbench-master/.bzrignore 
Processing /mnt/dedisbench-master/dist_personalfiles 
Processing /mnt/dedisbench-master/Makefile.in 
Processing /mnt/dedisbench-master/missing 
Processing /mnt/dedisbench-master/configure 
Processing /mnt/dedisbench-master/.DS_Store 
Processing /mnt/dedisbench-master/NEWS 
Processing /mnt/dedisbench-master/configure.scan 
Processing /mnt/dedisbench-master/berk.c 
Processing /mnt/dedisbench-master/.deps/DEDISgen-DEDISgen.Po 
Processing /mnt/dedisbench-master/.deps/DEDISgenutils-DEDISgen-utils.Po 
Processing /mnt/dedisbench-master/.deps/DEDISbench-DEDISbench.Po 
Processing /mnt/dedisbench-master/autoscan.log 
Processing /mnt/dedisbench-master/Makefile 
Processing /mnt/dedisbench-master/DEDISgen-utils.c 
Processing /mnt/dedisbench_0010test3 
processed 600000 blocks
processed 700000 blocks
processed 800000 blocks
processed 900000 blocks
processed 1000000 blocks
Processing /mnt/dedisbench_0010test2 
processed 1100000 blocks
processed 1200000 blocks
processed 1300000 blocks
processed 1400000 blocks
processed 1500000 blocks
Processing /mnt/dedisbench_0010test0 
processed 1600000 blocks
processed 1700000 blocks
processed 1800000 blocks
processed 1900000 blocks
processed 2000000 blocks
files scanned 73
total blocks scanned 2097616
total blocks with zeros appended 0
blocks without duplicates 840376
distinct blocks with duplicates 15142
duplicated blocks 1242098
space saved 5087633408
before generating output dist
before printing output dist

#####
Running under sudo appears to correct the problem. This leads us to believe that it's a permissions issue. It's not clear which file/folder's permissions are at fault, however, and running the tool under sudo under normal operating circumstances isn't plausible.

**Comment by jtpaulo** [comment] 2015-08-04 12:52
Hello, 

Ok so the two problems are identified: One is the DB folders path and the other is related with the folders permissions.

I am currently on vacations so I cannot fix these issues immediately, I will try to do it as soon as possible.

Thank you for the info

Regards, 

João Paulo

**Comment by jtpaulo** [comment] 2015-08-16 16:54
Hello Ramón,

I had the time to look further at these two issues and:
- I have committed a new version that automatically creates the DB folders in the directory you are executing DEDISgen
- The other issue was due to calling the -o flag without specifying the file name in the path. In your example you were using "-o/home/dedis/Desktop/" but you should include also the new filename in the path. For instance if you want to generate a distribution and save it in file "dist" you should use "-o/home/dedis/Desktop/dist"

The README was updated to make this flag more clear

Regards, 

João Paulo

**Closed as completed by jtpaulo** 2015-08-16 16:54 UTC
